name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # windows-latest
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]  #

    steps:
    - uses: actions/checkout@v4

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a


    - uses: mamba-org/setup-micromamba@v1
      with:
        python-version: ${{ matrix.python-version }}
        init-shell: bash
        environment-file:  dev/conda-env/test_env.yaml

    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list


    - name: Run tests
      shell: bash -l {0}
      run: |
        python setup.py install
        pytest -v --color=yes serenityff/charge/tests/ --cov=serenityff --cov-report=xml

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: ${{ github.repository.private == false }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ python ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        if: ${{ matrix.language == 'javascript' || matrix.language == 'python' }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"

  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ github.repository.private == false }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
